### ISSUE TITLE
Error during `npm run setup`

### ISSUE THREAD

**Issue by rpiwetz** [thebakeryio/baker#63]
I was able to clone, install, and setup successfully once, but now I receive the below error after running these commands:

```
git clone https://github.com/thebakeryio/baker.git MyApp
cd MyApp && npm install && npm run setup  
```

> baker run ./.baker/generate.js app
> module.js:471
>     throw err;
>     ^
> Error: Cannot find module './src/init'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)

**Comment by rpiwetz** [comment]
Cloned and re-ran the install/setup commands this morning and it is working now...closing issue.
