### ISSUE TITLE
setup command fails

### ISSUE THREAD

**Issue by jcollum** [thebakeryio/baker#74]
```
 $  git clone https://github.com/thebakeryio/baker.git MyReactNativeApp
 $  cd MyReactNativeApp && npm install && npm run setup 

$ npm run setup

> baker@1.2.1 setup /Users/collumj/research/MyReactNativeApp
> baker run ./.baker/generate.js app

#
# I ran this twice to be sure
#

 conflict server  
? Overwrite server? overwrite this and all others
    force server
   create /Users/collumj/research/MyReactNativeApp/server/package.json
   create /Users/collumj/research/MyReactNativeApp/server/Procfile
   create /Users/collumj/research/MyReactNativeApp/server/public/images/logo.png
   create /Users/collumj/research/MyReactNativeApp/server/src/graphql/index.js
   create /Users/collumj/research/MyReactNativeApp/server/src/graphql/schema.js
   create /Users/collumj/research/MyReactNativeApp/server/src/index.js
   create /Users/collumj/research/MyReactNativeApp/server/src/parse-server/index.js
   create /Users/collumj/research/MyReactNativeApp/server/tests/.eslintrc
   create /Users/collumj/research/MyReactNativeApp/server/tests/example.test.js
    force app/assets
   create /Users/collumj/research/MyReactNativeApp/app/assets/config.json
   create /Users/collumj/research/MyReactNativeApp/app/assets/icon.png
    force app/package.json
Error: Could not find or load main class install
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: yarn install
Error: Could not find or load main class install

```

Yarn install? I don't have yarn. The docs don't say that's required. Yarn sounds nice but I don't think there's anyway it's ready to be something you can assume people have.

**Comment by callmephilip** [comment]
Could you please provide more information regarding the platform you are running this on + node and npm versions.  Baker uses yarn under the hood if it thinks it's available on your machine, otherwise it falls back to npm. 

Also, what did you get when you ran ```npm run setup``` for the first time?

**Comment by jcollum** [comment]
```
$ versions
npm 3.10.8
node v6.9.1
OS Darwin *** 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

Output of the install (no different that I can see): 

```
$ git clone https://github.com/thebakeryio/baker.git MyReactNativeApp
Cloning into 'MyReactNativeApp'...
remote: Counting objects: 1255, done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 1255 (delta 38), reused 0 (delta 0), pack-reused 1161
Receiving objects: 100% (1255/1255), 752.41 KiB | 569.00 KiB/s, done.
Resolving deltas: 100% (587/587), done.
Checking connectivity... done.

collumj@por-collumj-m ~/research (development) 07:42:30  
$ cd MyReactNativeApp && npm install && npm run setup 
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> baker@1.2.1 preinstall /Users/collumj/research/MyReactNativeApp
> ./.baker/check-npm-version.js


> fsevents@1.0.15 install /Users/collumj/research/MyReactNativeApp/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/collumj/research/MyReactNativeApp/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> spawn-sync@1.0.15 postinstall /Users/collumj/research/MyReactNativeApp/node_modules/spawn-sync
> node postinstall

baker@1.2.1 /Users/collumj/research/MyReactNativeApp
├─┬ baker-scripts@0.9.0 
│ ├─┬ babel-cli@6.18.0 

  [rest of the tree]


> baker@1.2.1 setup /Users/collumj/research/MyReactNativeApp
> baker run ./.baker/generate.js app

   create server
   create /Users/collumj/research/MyReactNativeApp/server/package.json
   create /Users/collumj/research/MyReactNativeApp/server/Procfile
   create /Users/collumj/research/MyReactNativeApp/server/public/images/logo.png
   create /Users/collumj/research/MyReactNativeApp/server/src/graphql/index.js
   create /Users/collumj/research/MyReactNativeApp/server/src/graphql/schema.js
   create /Users/collumj/research/MyReactNativeApp/server/src/index.js
   create /Users/collumj/research/MyReactNativeApp/server/src/parse-server/index.js
   create /Users/collumj/research/MyReactNativeApp/server/tests/.eslintrc
   create /Users/collumj/research/MyReactNativeApp/server/tests/example.test.js
   create app/assets
   create /Users/collumj/research/MyReactNativeApp/app/assets/config.json
   create /Users/collumj/research/MyReactNativeApp/app/assets/icon.png
   create app/package.json
Error: Could not find or load main class install
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: yarn install
Error: Could not find or load main class install

    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at constructor.installAppDepsAndRunRNSetup (/Users/collumj/research/MyReactNativeApp/.baker/generators/app/index.js:57:7)
    at Object.<anonymous> (/Users/collumj/research/MyReactNativeApp/node_modules/yeoman-generator/lib/base.js:439:23)
    at /Users/collumj/research/MyReactNativeApp/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /Users/collumj/research/MyReactNativeApp/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /Users/collumj/research/MyReactNativeApp/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```

**Comment by callmephilip** [comment]
do you have yarn installed on your system and if you do what version is it?

**Comment by jcollum** [comment]
Well at first I thought "no, I haven't installed yarn". But then: 

```
$ which yarn
/usr/local/bin/yarn

```

What? 

```
collumj@por-collumj-m ~/research (development) 10:31:57  
$ yarn version
Hadoop 2.7.2
```

Oh. There's a Hadoop tool called Yarn.  http://hortonworks.com/apache/yarn/. It appears that Yarn may have a bit of a conflict if someone is using Hadoop.

**Comment by callmephilip** [comment]
oh wow

**Comment by jcollum** [comment]
Yeah it surprised me too.

**Comment by jcollum** [comment]
Easily fixed though: 

`$ brew uninstall hadoop` 

because fuck hadoop. 💯

**Comment by callmephilip** [comment]
so based on this: https://github.com/yarnpkg/yarn/issues/673. i'd say we will probably end up using **yarnpkg** alias instead

**Comment by callmephilip** [comment]
thanks for reporting this and helping with debugging

**Comment by jcollum** [comment]
Hey thank you for being responsive and nice about it.
